### ISSUE TITLE
Does not work on Android devices

### ISSUE THREAD

**Issue by AlekseySorokin** [angel-vladov/ngx-pattern#17]
You can make sure of it on a demo page.
Enter with Android
https://angel-vladov.github.io/ngx-pattern/

**Comment by AlekseySorokin** [comment]
The reason is event keydown on Android devices. It doesn't give the corrected key property.

**Comment by angel-vladov** [comment]
Thanks for reporting it. I'll push a fix for that.

**Comment by angel-vladov** [comment]
@AlekseySorokin I've published a new version of the library `0.2.1` that should solve the issue you have and work on Android.
